age = input("How old are you? ")
print(f"On your next birthday, you will be "+ str((int(age) + 1)))
print ()
eggs = input("how many egg cartons do you have? ")
print(f"you have "+ str((int(eggs) * 12))+ " eggs")
print ()
cookies = input("how many cookies do you have? ")
people = input("How many people are there? ")
print(f"Each person may have "+ str((float(cookies) / float(people)))+ " cookies")
