print ("Please enter the following: ")
adjective = input("adjective: ")
animal = input("animal: ")
verb1 = input("verb: ")
exclamation = input("exclamation: ")
verb2 = input("verb : ")
verb3 = input("verb: ")
print ()
print ("Your story is: ")
print ()
print (f"The other day, I was really in trouble. It all started when I saw a very")
print (f'{adjective} {animal} {verb1} sneeze down the hallway. "{exclamation}!" I yelled. But all')
print (f"I could think to do was to {verb2} over and over. Miraculously,")
print (f"that caused it to stop, but not before it tried to {verb3}")
print (f"right in front of my family. ")

# I made it my own during this part forward, I added a second part of the story asking different information
# to the person to keep going with the story 
print ()
print ()
print ()
print ()

print ("Keep going with the second part of the story...")
print ("Please enter the following: ")
day = input("day of the week: ")
animal1 = input("animal: ")
adjective1 = input("adjective: ")
exclamation1 = input("exclamation: ")
verb4 = input("verb : ")
place = input("place: ")
print ()
print ("The second part is: ")
print ()
print (f"I almost died during that time, but on {day}")
print (f'I saw a {animal1} and it was so {adjective1}')
print (f"I tried to {verb4} but it was useless so I hurted myself and went to the {place}  ")
print (f"to watch TV :) ")

print ("THE END OF THE STORY!")

